version : "3"

services:
  lb:
    image: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  app:
    image: hermes-chat
    volumes:
      - ./env/prod.json:/build/env/env.json
    environment:
      - SERVER="1"

